version: '3.1'

services:

  maro_db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: NotSafeForProd
      MYSQL_DATABASE: maro-challenge
      MYSQL_USER: maro
      MYSQL_PASSWORD: NotSafeForProd

  maro_adminer:
    image: adminer
    ports:
      - 8080:8080